"""Member-management domain shared by HTTP, CLI, and the worker."""

from telegram_assistant.members.service import (
    BulkMemberAddFailed,
    BulkMemberAddNeedsReview,
    BulkMemberAddPending,
    BulkMemberAddRequest,
    BulkMemberAddResult,
    BulkMemberItem,
    BulkMemberItemResult,
    BulkMemberRemoveFailed,
    BulkMemberRemoveItem,
    BulkMemberRemoveItemResult,
    BulkMemberRemoveNeedsReview,
    BulkMemberRemovePending,
    BulkMemberRemoveRequest,
    BulkMemberRemoveResult,
    MemberAddBackend,
    MemberAddError,
    MemberAlreadyPresentError,
    MemberNotPresentError,
    MemberPrivacyError,
    MemberRemoveBackend,
    NormalizedMember,
    bulk_add_members,
    bulk_remove_members,
    normalize_user_ref,
    protected_user_set,
)

__all__ = [
    "BulkMemberAddFailed",
    "BulkMemberAddNeedsReview",
    "BulkMemberAddPending",
    "BulkMemberAddRequest",
    "BulkMemberAddResult",
    "BulkMemberItem",
    "BulkMemberItemResult",
    "BulkMemberRemoveFailed",
    "BulkMemberRemoveItem",
    "BulkMemberRemoveItemResult",
    "BulkMemberRemoveNeedsReview",
    "BulkMemberRemovePending",
    "BulkMemberRemoveRequest",
    "BulkMemberRemoveResult",
    "MemberAddBackend",
    "MemberAddError",
    "MemberAlreadyPresentError",
    "MemberNotPresentError",
    "MemberPrivacyError",
    "MemberRemoveBackend",
    "NormalizedMember",
    "bulk_add_members",
    "bulk_remove_members",
    "normalize_user_ref",
    "protected_user_set",
]
