"""Group-creation domain shared by HTTP, CLI, and the worker."""

from telegram_assistant.groups.service import (
    GroupBackend,
    GroupCreateFailed,
    GroupCreateNeedsReview,
    GroupCreatePending,
    GroupCreateRequest,
    GroupCreateResult,
    GroupError,
    GroupLayoutSetFailed,
    GroupLayoutSetNeedsReview,
    GroupLayoutSetPending,
    GroupRenameFailed,
    GroupRenameNeedsReview,
    GroupRenamePending,
    GroupRenameRequest,
    GroupRenameResult,
    LayoutSetRequest,
    LayoutSetResult,
    create_group,
    get_topics_layout,
    rename_group,
    set_topics_layout,
)

__all__ = [
    "GroupBackend",
    "GroupCreateFailed",
    "GroupCreateNeedsReview",
    "GroupCreatePending",
    "GroupCreateRequest",
    "GroupCreateResult",
    "GroupError",
    "GroupLayoutSetFailed",
    "GroupLayoutSetNeedsReview",
    "GroupLayoutSetPending",
    "GroupRenameFailed",
    "GroupRenameNeedsReview",
    "GroupRenamePending",
    "GroupRenameRequest",
    "GroupRenameResult",
    "LayoutSetRequest",
    "LayoutSetResult",
    "create_group",
    "get_topics_layout",
    "rename_group",
    "set_topics_layout",
]
